import type { Category, CollectionName, Product } from "./types.ts";

/** A catalogue product before the database assigns its id. */
export type SeedProduct = Omit<Product, "id">;

/** A category tile before the database assigns its id (sortOrder = array index). */
export type SeedCategory = { name: Category; image: string; blurb: string };

/** A collection before the database assigns its id (sortOrder = array index). */
export type SeedCollection = {
  name: CollectionName;
  title: string;
  description: string;
  image: string;
};

/** Verified Unsplash photo ids used across the catalogue. */
const img = (id: string, w = 1200) =>
  `https://images.unsplash.com/photo-${id}?q=80&w=${w}&auto=format&fit=crop`;

export const seedProducts: SeedProduct[] = [
  {
    slug: "aurelia-pendant-necklace",
    name: "Aurelia Pendant Necklace",
    category: "Necklaces",
    collection: "Modern Muse",
    material: "18K Gold Plated",
    price: 2499,
    compareAtPrice: 3299,
    images: [img("1610694955371-d4a3e0ce4b52"), img("1611085583191-a3b181a88401")],
    shortDescription: "A whisper-fine chain with a hand-set solitaire pendant.",
    description:
      "The Aurelia is our love letter to quiet luxury — a whisper-fine 18K gold plated chain carrying a single hand-set stone that catches light with every turn. Designed to be worn alone or layered, it moves from morning meetings to evening celebrations without missing a beat.",
    rating: 0,
    reviewCount: 0,
    isBestseller: true,
    inStock: true,
    tags: ["pendant", "layering", "minimal"],
  },
  {
    slug: "seraphine-gold-choker",
    name: "Seraphine Gold Choker",
    category: "Chokers",
    collection: "Heritage",
    material: "18K Gold Plated",
    price: 3999,
    compareAtPrice: 4999,
    images: [img("1601121141461-9d6647bca1ed"), img("1618403088890-3d9ff6f4c8b1")],
    shortDescription: "Sculptural choker inspired by temple architecture.",
    description:
      "Inspired by the carved arches of South Indian temple architecture, the Seraphine choker sits close to the collarbone with a sculptural, almost architectural presence. Each link is individually polished for a mirror finish that reads as solid gold.",
    rating: 0,
    reviewCount: 0,
    isBestseller: true,
    inStock: true,
    tags: ["statement", "traditional", "festive"],
  },
  {
    slug: "luna-pearl-drop-earrings",
    name: "Luna Pearl Drop Earrings",
    category: "Earrings",
    collection: "Everyday Luxe",
    material: "Pearl",
    price: 1299,
    images: [img("1515562141207-7a88fb7ce338"), img("1617038220319-276d3cfab638")],
    shortDescription: "Freshwater pearls suspended from gold vermeil hooks.",
    description:
      "Luminous freshwater pearls suspended from delicate gold vermeil hooks. The Luna earrings sway gently as you move, framing the face with a soft, romantic glow that flatters every skin tone.",
    rating: 0,
    reviewCount: 0,
    isNew: true,
    inStock: true,
    tags: ["pearl", "drops", "romantic"],
  },
  {
    slug: "isabeau-diamond-look-studs",
    name: "Isabeau Diamond-Look Studs",
    category: "Diamond Look",
    collection: "Modern Muse",
    material: "American Diamond",
    price: 1999,
    compareAtPrice: 2799,
    images: [img("1589128777073-263566ae5e4d"), img("1598560917505-59a3ad559071")],
    shortDescription: "Brilliant-cut solitaire studs with a fire like the real thing.",
    description:
      "Cut and calibrated to mimic the fire of a natural solitaire, the Isabeau studs bring effortless brilliance to every day. Set in rhodium-finished prongs that never overshadow the stone.",
    rating: 0,
    reviewCount: 0,
    inStock: true,
    tags: ["studs", "solitaire", "office"],
  },
  {
    slug: "vasanta-antique-haram",
    name: "Vasanta Antique Haram",
    category: "Harams",
    collection: "Heritage",
    material: "Kundan",
    price: 8999,
    compareAtPrice: 11999,
    images: [img("1571908599407-cdb918ed83bf"), img("1601121141461-9d6647bca1ed")],
    shortDescription: "A regal long haram with hand-pressed kundan work.",
    description:
      "The Vasanta haram carries generations of craft in every motif. Hand-pressed kundan stones are set into an antique gold finish that deepens beautifully with wear — a family heirloom from the day it arrives.",
    rating: 0,
    reviewCount: 0,
    isBestseller: true,
    inStock: true,
    tags: ["haram", "kundan", "wedding"],
  },
  {
    slug: "eclat-bridal-set",
    name: "Muhurtham Bridal Set",
    category: "Bridal",
    collection: "Muhurtham Bridal",
    material: "Kundan",
    price: 12999,
    compareAtPrice: 15999,
    images: [img("1618403088890-3d9ff6f4c8b1"), img("1583937443566-6fe1a1c6e400")],
    shortDescription: "Complete bridal parure — necklace, earrings and maang tikka.",
    description:
      "Our signature bridal parure: a cascading kundan necklace, chandelier earrings and a maang tikka designed as one continuous composition. Muhurtham is made for the day every eye in the room is on you.",
    rating: 0,
    reviewCount: 0,
    isBestseller: true,
    inStock: true,
    tags: ["bridal", "set", "kundan"],
  },
  {
    slug: "noor-anti-tarnish-chain",
    name: "Noor Anti-Tarnish Chain",
    category: "Anti-Tarnish",
    collection: "Everyday Luxe",
    material: "Anti-Tarnish Alloy",
    price: 1499,
    images: [img("1599459183200-59c7687a0275"), img("1602173574767-37ac01994b2a")],
    shortDescription: "Waterproof, sweatproof, life-proof herringbone chain.",
    description:
      "Wear it in the shower, to the gym, on the beach. The Noor herringbone chain is triple-sealed with our anti-tarnish coating so it keeps its liquid-gold shine through everything your week throws at it.",
    rating: 0,
    reviewCount: 0,
    isNew: true,
    isBestseller: true,
    inStock: true,
    tags: ["anti-tarnish", "waterproof", "herringbone"],
  },
  {
    slug: "celeste-layered-chain",
    name: "Celeste Layered Chain",
    category: "Chains",
    collection: "Modern Muse",
    material: "18K Gold Plated",
    price: 1799,
    compareAtPrice: 2299,
    images: [img("1635767798638-3e25273a8236"), img("1531995811006-35cb42e1a022")],
    shortDescription: "Three chains, one clasp — the effortless layered look.",
    description:
      "Three graduated chains joined at a single clasp, so you get the perfectly-styled layered look without the tangle. Celeste is the piece our studio team reaches for most.",
    rating: 0,
    reviewCount: 0,
    inStock: true,
    tags: ["layered", "chains", "minimal"],
  },
  {
    slug: "margot-sculpted-hoops",
    name: "Margot Sculpted Hoops",
    category: "Earrings",
    collection: "Modern Muse",
    material: "18K Gold Plated",
    price: 1599,
    images: [img("1631982690223-8aa4be0a2497"), img("1617038220319-276d3cfab638")],
    shortDescription: "Bold, organically sculpted hoops with a satin finish.",
    description:
      "Organic, almost molten in form, the Margot hoops are cast in a satin gold finish that photographs like sunlight. Feather-light despite their presence — you will forget you are wearing them.",
    rating: 0,
    reviewCount: 0,
    isBestseller: true,
    inStock: true,
    tags: ["hoops", "statement", "everyday"],
  },
  {
    slug: "priya-temple-necklace",
    name: "Priya Temple Necklace",
    category: "Necklaces",
    collection: "Heritage",
    material: "18K Gold Plated",
    price: 5999,
    compareAtPrice: 7499,
    images: [img("1617117811969-97f441511dee"), img("1601121141461-9d6647bca1ed")],
    shortDescription: "Goddess Lakshmi motifs in antique gold finish.",
    description:
      "Hand-finished Lakshmi motifs march along this classic temple necklace, each one burnished to an antique glow. Priya pairs as beautifully with a Kanjeevaram as it does with a plain black dress.",
    rating: 0,
    reviewCount: 0,
    inStock: true,
    tags: ["temple", "traditional", "festive"],
  },
  {
    slug: "ondine-silver-ring",
    name: "Ondine Silver Ring",
    category: "Accessories",
    collection: "Modern Muse",
    material: "92.5 Silver",
    price: 1299,
    images: [img("1608042314453-ae338d80c427"), img("1596944924616-7b38e7cfac36")],
    shortDescription: "A fluid wave of solid 92.5 silver.",
    description:
      "One continuous wave of solid 92.5 sterling silver, polished until it flows like water around the finger. Ondine stacks beautifully or stands alone as a quiet signature.",
    rating: 0,
    reviewCount: 0,
    inStock: true,
    tags: ["ring", "silver", "stacking"],
  },
  {
    slug: "amara-solitaire-ring",
    name: "Amara Solitaire Ring",
    category: "Diamond Look",
    collection: "Muhurtham Bridal",
    material: "American Diamond",
    price: 2999,
    compareAtPrice: 3999,
    images: [img("1605100804763-247f67b3557e"), img("1596944924616-7b38e7cfac36")],
    shortDescription: "The proposal-worthy solitaire, without the price tag.",
    description:
      "A cathedral-set brilliant that holds its own against stones ten times its price. The Amara solitaire is our most-gifted ring — and our most photographed.",
    rating: 0,
    reviewCount: 0,
    isBestseller: true,
    inStock: true,
    tags: ["ring", "solitaire", "gift"],
  },
  {
    slug: "zaria-chandbali-earrings",
    name: "Zaria Chandbali Earrings",
    category: "Earrings",
    collection: "Heritage",
    material: "Kundan",
    price: 2799,
    compareAtPrice: 3499,
    images: [img("1630019852942-f89202989a59"), img("1535632066927-ab7c9ab60908")],
    shortDescription: "Crescent chandbalis with hanging pearl fringe.",
    description:
      "The eternal crescent, reimagined. Zaria's chandbali silhouette carries a fringe of seed pearls that dance with every step — festive dressing at its most graceful.",
    rating: 0,
    reviewCount: 0,
    inStock: true,
    tags: ["chandbali", "festive", "pearl"],
  },
  {
    slug: "vera-tennis-bracelet",
    name: "Vera Tennis Bracelet",
    category: "Diamond Look",
    collection: "Modern Muse",
    material: "American Diamond",
    price: 3499,
    images: [img("1619119069152-a2b331eb392a"), img("1573408301185-9146fe634ad0")],
    shortDescription: "An unbroken line of brilliance around the wrist.",
    description:
      "Forty-two calibrated stones in a continuous channel setting. The Vera tennis bracelet is engineered to flex with the wrist while reading as a single unbroken line of light.",
    rating: 0,
    reviewCount: 0,
    isNew: true,
    inStock: true,
    tags: ["bracelet", "tennis", "evening"],
  },
  {
    slug: "kanak-bridal-choker",
    name: "Kanak Bridal Choker",
    category: "Bridal",
    collection: "Muhurtham Bridal",
    material: "Kundan",
    price: 7999,
    compareAtPrice: 9999,
    images: [img("1535632066927-ab7c9ab60908"), img("1601121141461-9d6647bca1ed")],
    shortDescription: "Dense kundan choker with emerald-green drops.",
    description:
      "A dense field of hand-set kundan punctuated by emerald-green drops. Kanak sits high and proud on the neckline — the anchor piece of a bridal trousseau.",
    rating: 0,
    reviewCount: 0,
    inStock: true,
    tags: ["bridal", "choker", "kundan"],
  },
  {
    slug: "sylvie-snake-chain",
    name: "Sylvie Snake Chain",
    category: "Chains",
    collection: "Everyday Luxe",
    material: "Anti-Tarnish Alloy",
    price: 1299,
    images: [img("1600721391689-2564bb8055de"), img("1602173574767-37ac01994b2a")],
    shortDescription: "Liquid-smooth snake chain in a mirror gold finish.",
    description:
      "Smooth as poured metal, the Sylvie snake chain catches light along its entire length. Anti-tarnish sealed, it is the layering essential that starts every neck stack.",
    rating: 0,
    reviewCount: 0,
    inStock: true,
    tags: ["chain", "layering", "anti-tarnish"],
  },
  {
    slug: "rhea-emerald-choker",
    name: "Rhea Emerald Choker",
    category: "Chokers",
    collection: "Heritage",
    material: "Kundan",
    price: 4999,
    compareAtPrice: 6499,
    images: [img("1618403088890-3d9ff6f4c8b1"), img("1535632066927-ab7c9ab60908")],
    shortDescription: "Deep green stones ringed by antique gold beadwork.",
    description:
      "Deep, forest-green stones ringed with hand-applied gold beadwork. The Rhea choker brings old-world opulence to modern silhouettes — worn best with a bare neckline.",
    rating: 0,
    reviewCount: 0,
    inStock: true,
    tags: ["choker", "emerald", "festive"],
  },
  {
    slug: "elowen-station-necklace",
    name: "Elowen Station Necklace",
    category: "Necklaces",
    collection: "Everyday Luxe",
    material: "18K Gold Plated",
    price: 1899,
    images: [img("1611085583191-a3b181a88401"), img("1610694955371-d4a3e0ce4b52")],
    shortDescription: "Tiny bezel stations spaced along a fine gold chain.",
    description:
      "Seven tiny bezel-set stations spaced along a fine chain — the Elowen adds the subtlest glimmer above a crew neck or under a shirt collar. Quietly perfect.",
    rating: 0,
    reviewCount: 0,
    isNew: true,
    inStock: true,
    tags: ["station", "minimal", "layering"],
  },
  {
    slug: "aisha-jhumka-earrings",
    name: "Aisha Jhumka Earrings",
    category: "Earrings",
    collection: "Heritage",
    material: "18K Gold Plated",
    price: 2199,
    compareAtPrice: 2999,
    images: [img("1617038220319-276d3cfab638"), img("1535632066927-ab7c9ab60908")],
    shortDescription: "Classic domed jhumkas with a modern matte finish.",
    description:
      "The classic domed jhumka, re-cut with cleaner lines and a modern matte-gold finish. Aisha bridges heirloom and contemporary — festive enough for a wedding, easy enough for Friday dinner.",
    rating: 0,
    reviewCount: 0,
    isBestseller: true,
    inStock: true,
    tags: ["jhumka", "traditional", "festive"],
  },
  {
    slug: "mira-pearl-strand",
    name: "Mira Pearl Strand",
    category: "Necklaces",
    collection: "Everyday Luxe",
    material: "Pearl",
    price: 2299,
    images: [img("1531995811006-35cb42e1a022"), img("1583937443566-6fe1a1c6e400")],
    shortDescription: "Hand-knotted freshwater pearls with a gold toggle.",
    description:
      "Individually hand-knotted freshwater pearls finished with a sculptural gold toggle clasp meant to be worn at the front. Mira is the modern way to wear pearls.",
    rating: 0,
    reviewCount: 0,
    inStock: true,
    tags: ["pearl", "strand", "modern"],
  },
  {
    slug: "devi-lakshmi-haram",
    name: "Devi Lakshmi Haram",
    category: "Harams",
    collection: "Heritage",
    material: "18K Gold Plated",
    price: 9999,
    compareAtPrice: 12999,
    images: [img("1601121141461-9d6647bca1ed"), img("1571908599407-cdb918ed83bf")],
    shortDescription: "Opera-length haram with coin and deity motifs.",
    description:
      "An opera-length haram strung with burnished coin and deity motifs, closing with an adjustable silk cord. Devi layers magnificently over the Priya temple necklace.",
    rating: 0,
    reviewCount: 0,
    inStock: true,
    tags: ["haram", "temple", "wedding"],
  },
  {
    slug: "sable-curb-chain",
    name: "Sable Curb Chain",
    category: "Chains",
    collection: "Modern Muse",
    material: "18K Gold Plated",
    price: 2499,
    images: [img("1543294001-f7cd5d7fb516"), img("1602173574767-37ac01994b2a")],
    shortDescription: "A confident curb link with softened, rounded edges.",
    description:
      "A confident curb-link chain with every edge softened and rounded for comfort. Sable is unisex by design — substantial without ever being loud.",
    rating: 0,
    reviewCount: 0,
    inStock: true,
    tags: ["curb", "unisex", "statement"],
  },
  {
    slug: "fleur-ear-cuff-set",
    name: "Fleur Ear Cuff Set",
    category: "Earrings",
    collection: "Modern Muse",
    material: "Anti-Tarnish Alloy",
    price: 999,
    compareAtPrice: 1399,
    images: [img("1506630448388-4e683c67ddb0"), img("1631982690223-8aa4be0a2497")],
    shortDescription: "Three sculpted cuffs — no piercings required.",
    description:
      "Three sculpted cuffs in graduated sizes, designed to climb the ear in a single sweep. No piercings required, endless combinations possible.",
    rating: 0,
    reviewCount: 0,
    isNew: true,
    inStock: true,
    tags: ["ear cuff", "set", "edgy"],
  },
  {
    slug: "ravenna-cocktail-ring",
    name: "Ravenna Cocktail Ring",
    category: "Accessories",
    collection: "Modern Muse",
    material: "American Diamond",
    price: 1999,
    images: [img("1603561591411-07134e71a2a9"), img("1617117811969-97f441511dee")],
    shortDescription: "An oversized emerald-cut stone in a bold gold bezel.",
    description:
      "An oversized emerald-cut stone caught in a heavy gold bezel — the Ravenna is pure evening drama, made to be seen across the room.",
    rating: 0,
    reviewCount: 0,
    inStock: true,
    tags: ["cocktail", "ring", "evening"],
  },
  {
    slug: "ines-bridal-earrings",
    name: "Inès Bridal Chandeliers",
    category: "Bridal",
    collection: "Muhurtham Bridal",
    material: "American Diamond",
    price: 4499,
    compareAtPrice: 5999,
    images: [img("1573408301185-9146fe634ad0"), img("1535632066927-ab7c9ab60908")],
    shortDescription: "Four-tier chandelier earrings that frame the face in light.",
    description:
      "Four tiers of graduated stones cascade from a single stud — the Inès chandeliers were designed under veil lighting to frame the face in pure light.",
    rating: 0,
    reviewCount: 0,
    inStock: true,
    tags: ["bridal", "chandelier", "statement"],
  },
  {
    slug: "opaline-tarnish-free-hoops",
    name: "Opaline Tarnish-Free Hoops",
    category: "Anti-Tarnish",
    collection: "Everyday Luxe",
    material: "Anti-Tarnish Alloy",
    price: 1199,
    images: [img("1611591437281-460bfbe1220a"), img("1617038220319-276d3cfab638")],
    shortDescription: "Chunky hoops you never have to take off.",
    description:
      "Chunky, light-catching hoops sealed with our triple anti-tarnish coating. Sleep in them, swim in them — Opaline keeps its shine for years, guaranteed.",
    rating: 0,
    reviewCount: 0,
    isBestseller: true,
    inStock: true,
    tags: ["hoops", "anti-tarnish", "waterproof"],
  },
  {
    slug: "sonata-lariat-necklace",
    name: "Sonata Lariat Necklace",
    category: "Necklaces",
    collection: "Modern Muse",
    material: "18K Gold Plated",
    price: 2199,
    images: [img("1601821765780-754fa98637c1"), img("1610694955371-d4a3e0ce4b52")],
    shortDescription: "A drop lariat that traces the neckline like a brushstroke.",
    description:
      "One fluid line dropping into a Y-silhouette, ending in a polished teardrop. The Sonata lariat traces the neckline like a single brushstroke — made for open collars and evening necklines.",
    rating: 0,
    reviewCount: 0,
    isNew: true,
    inStock: true,
    tags: ["lariat", "minimal", "evening"],
  },
  {
    slug: "gitanjali-bridal-haram",
    name: "Gitanjali Bridal Haram",
    category: "Bridal",
    collection: "Muhurtham Bridal",
    material: "Kundan",
    price: 11999,
    compareAtPrice: 14999,
    images: [img("1583937443566-6fe1a1c6e400"), img("1571908599407-cdb918ed83bf")],
    shortDescription: "A cascading three-layer haram for the grandest entrance.",
    description:
      "Three cascading layers of kundan and pearl, engineered to sit flat and move as one. Gitanjali is our most elaborate bridal piece — built for the grandest of entrances.",
    rating: 0,
    reviewCount: 0,
    inStock: true,
    tags: ["bridal", "haram", "layered"],
  },
  {
    slug: "etta-box-chain-anklet",
    name: "Etta Box Chain Anklet",
    category: "Accessories",
    collection: "Everyday Luxe",
    material: "Anti-Tarnish Alloy",
    price: 899,
    images: [img("1588444837495-c6cfeb53f32d"), img("1611591437281-460bfbe1220a")],
    shortDescription: "A fine box chain anklet with a single bezel charm.",
    description:
      "A fine box-link anklet carrying one tiny bezel-set charm. Etta is summer distilled — waterproof, tarnish-free and barely there.",
    rating: 0,
    reviewCount: 0,
    inStock: true,
    tags: ["anklet", "summer", "anti-tarnish"],
  },
  {
    slug: "cassia-collar-choker",
    name: "Cassia Collar Choker",
    category: "Chokers",
    collection: "Modern Muse",
    material: "18K Gold Plated",
    price: 2999,
    compareAtPrice: 3799,
    images: [img("1620656798579-1984d9e87df7"), img("1600721391689-2564bb8055de")],
    shortDescription: "A rigid open collar with sculpted gold end-caps.",
    description:
      "A rigid open collar finished with two sculpted end-caps that sit just off-centre at the throat. Cassia is minimalism with a spine — striking over turtlenecks and bare skin alike.",
    rating: 0,
    reviewCount: 0,
    isNew: true,
    inStock: true,
    tags: ["collar", "minimal", "sculptural"],
  },
  {
    slug: "nyra-eternity-band",
    name: "Nyra Eternity Band",
    category: "Diamond Look",
    collection: "Muhurtham Bridal",
    material: "American Diamond",
    price: 1799,
    images: [img("1596944924616-7b38e7cfac36"), img("1605100804763-247f67b3557e")],
    shortDescription: "A full circle of pavé stones, symbol of the unbroken.",
    description:
      "Pavé stones circle the full band with no beginning and no end. The Nyra eternity band stacks with the Amara solitaire or speaks quietly on its own.",
    rating: 0,
    reviewCount: 0,
    inStock: true,
    tags: ["band", "stacking", "gift"],
  },
  {
    slug: "veda-coin-pendant",
    name: "Veda Coin Pendant",
    category: "Anti-Tarnish",
    collection: "Heritage",
    material: "Anti-Tarnish Alloy",
    price: 1599,
    compareAtPrice: 1999,
    images: [img("1635767798638-3e25273a8236"), img("1543294001-f7cd5d7fb516")],
    shortDescription: "An antique coin motif on a tarnish-free rope chain.",
    description:
      "A hand-antiqued coin motif suspended from a tarnish-free rope chain. Veda carries the weight of heritage with none of the upkeep — polish-free forever.",
    rating: 0,
    reviewCount: 0,
    inStock: true,
    tags: ["coin", "pendant", "heritage"],
  },
  {
    slug: "halcyon-two-tone-ring",
    name: "Halcyon Two-Tone Ring",
    category: "Accessories",
    collection: "Modern Muse",
    material: "92.5 Silver",
    price: 1499,
    images: [img("1602752250015-52934bc45613"), img("1620656798579-1984d9e87df7")],
    shortDescription: "Interlocked bands of silver and gold vermeil.",
    description:
      "Two interlocked bands — one polished silver, one gold vermeil — that rotate freely around each other. The Halcyon is a quiet fidget and a modern classic in one.",
    rating: 0,
    reviewCount: 0,
    isNew: true,
    inStock: true,
    tags: ["ring", "two-tone", "modern"],
  },
  {
    slug: "banaras-polki-necklace",
    name: "Banaras Polki Necklace",
    category: "Necklaces",
    collection: "Heritage",
    material: "Kundan",
    price: 6999,
    compareAtPrice: 8999,
    images: [img("1601121141461-9d6647bca1ed"), img("1583937443566-6fe1a1c6e400")],
    shortDescription: "Uncut polki stones in a classic bib silhouette.",
    description:
      "Uncut polki-style stones set shoulder to shoulder in a classic bib silhouette. Banaras glows rather than sparkles — the unmistakable warmth of old-world jewellery.",
    rating: 0,
    reviewCount: 0,
    inStock: false,
    tags: ["polki", "bib", "festive"],
  },
  {
    slug: "wren-threader-earrings",
    name: "Wren Threader Earrings",
    category: "Earrings",
    collection: "Everyday Luxe",
    material: "92.5 Silver",
    price: 1099,
    images: [img("1598560917505-59a3ad559071"), img("1631982690223-8aa4be0a2497")],
    shortDescription: "Silver threaders that draw a fine line through the lobe.",
    description:
      "A single fine chain drawn through the lobe, ending in a polished bar. The Wren threaders are movement and minimalism in equal measure.",
    rating: 0,
    reviewCount: 0,
    inStock: true,
    tags: ["threader", "silver", "minimal"],
  },
  {
    slug: "surya-choker-haram-duo",
    name: "Surya Choker-Haram Duo",
    category: "Harams",
    collection: "Heritage",
    material: "18K Gold Plated",
    price: 10999,
    compareAtPrice: 13999,
    images: [img("1602173574767-37ac01994b2a"), img("1601121141461-9d6647bca1ed")],
    shortDescription: "A matched choker and haram, designed to be worn as one.",
    description:
      "A matched choker and opera-length haram composed as a single look — the traditional layered silhouette, ready in one box. Surya is the definitive festive statement.",
    rating: 0,
    reviewCount: 0,
    inStock: true,
    tags: ["duo", "layered", "wedding"],
  },
];

/**
 * Taxonomy seed defaults, copied verbatim from the storefront's original
 * static data (frontend src/data/site.ts). Seeded with $setOnInsert only, so
 * anything the admin edits or deletes afterwards is never clobbered.
 */
export const seedCategories: SeedCategory[] = [
  {
    name: "Necklaces",
    image: img("1610694955371-d4a3e0ce4b52"),
    blurb: "From whisper-fine pendants to temple classics",
  },
  {
    name: "Earrings",
    image: img("1617038220319-276d3cfab638"),
    blurb: "Studs, hoops, jhumkas and chandeliers",
  },
  {
    name: "Bridal",
    image: img("1583937443566-6fe1a1c6e400"),
    blurb: "Parures composed for your most beautiful beginning",
  },
  {
    name: "Anti-Tarnish",
    image: img("1599459183200-59c7687a0275"),
    blurb: "Waterproof shine you never take off",
  },
  {
    name: "Chokers",
    image: img("1618403088890-3d9ff6f4c8b1"),
    blurb: "Sculptural pieces that sit close and speak loudly",
  },
  {
    name: "Chains",
    image: img("1635767798638-3e25273a8236"),
    blurb: "The essentials every stack is built on",
  },
  {
    name: "Harams",
    image: img("1571908599407-cdb918ed83bf"),
    blurb: "Opera-length grandeur, hand-finished",
  },
  {
    name: "Diamond Look",
    image: img("1605100804763-247f67b3557e"),
    blurb: "The fire of solitaires, the freedom of everyday wear",
  },
  {
    name: "Accessories",
    image: img("1598560917505-59a3ad559071"),
    blurb: "Rings, anklets and finishing touches",
  },
];

export const seedCollections: SeedCollection[] = [
  {
    name: "Heritage",
    title: "The Heritage Collection",
    description:
      "Temple motifs, kundan work and antique finishes — centuries of Indian craft, composed for the way you dress today.",
    image: img("1601121141461-9d6647bca1ed", 1600),
  },
  {
    name: "Modern Muse",
    title: "Modern Muse",
    description:
      "Sculptural, fluid, quietly confident. Pieces that read like modern art and wear like second skin.",
    image: img("1600721391689-2564bb8055de", 1600),
  },
  {
    name: "Muhurtham Bridal",
    title: "Muhurtham Bridal",
    description:
      "Composed under veil lighting, engineered to move as one — parures for the day every eye is on you.",
    image: img("1583937443566-6fe1a1c6e400", 1600),
  },
  {
    name: "Everyday Luxe",
    title: "Everyday Luxe",
    description:
      "Waterproof, tarnish-free, barely-there luxury. The pieces you put on once and simply live in.",
    image: img("1599459183200-59c7687a0275", 1600),
  },
];
